# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68c15ce14037a3875304da5fd44063dbc844733a286b4a8b761f3587af004db601b39efb17636a82c49cff36873966f97e7f5d4027ae9e6f7210c136ce5595ac

test:
  secret_key_base: 666a31b6ce4552068b2b5ca499061d5407378912089ec680650715360eb295fefef6ecd97cf5208aeb9622831bbe20e44984caa2eef6b1fc93459834b771e90e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
